/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example;

import org.example.players.Human;
import org.example.players.Player;

import javax.swing.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Класс для работы с графическим пользовательским интерфейсом
 * @see javax.swing.JFrame
 * @author Мария
 */
public class JFrames extends javax.swing.JFrame {
    Game game = new Game();
    Human human = null;
    Player enemy = null;
    Items[] items = new Items[3];
    String nameButton = "";

    
    /**
     * Создание нового JFrame
     */
    public JFrames() {
        initComponents();
        try {
            game.xlsxManipulation.ReadFromExcel();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog (null, ex.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }
        game.xlsxManipulation.WriteToTable(jTableResult);
        
        buttonGroupItems.add(jRadioButtonSmallItem);
        buttonGroupItems.add(jRadioButtonBigItem);
        buttonGroupItems.add(jRadioButtonCrossRelive);

        buttonGroupFighter.add(jRadioButtonJhin);
        buttonGroupFighter.add(jRadioButtonKarina);
        buttonGroupFighter.add(jRadioButtonRammus);
        
        items[0]=new Items("Малое зелье лечение",0);
        items[1]=new Items("Большое зелье лечение",0);
        items[2]=new Items("Крест возрождения",0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame = new javax.swing.JFrame();
        jPanelGameplay = new javax.swing.JPanel();
        jLabelImageHuman = new javax.swing.JLabel();
        jButtonAtack = new javax.swing.JButton();
        jButtonDefence = new javax.swing.JButton();
        jProgressBarHumanDamage = new javax.swing.JProgressBar();
        jLabelImageEnemy = new javax.swing.JLabel();
        jProgressBarEnemyDamage = new javax.swing.JProgressBar();
        jLabelNameBoss = new javax.swing.JLabel();
        jLabelEnemyDamage = new javax.swing.JLabel();
        jLabelHumanDamage = new javax.swing.JLabel();
        jLabelHumanDamageValue = new javax.swing.JLabel();
        jLabelEnemyDamageValue = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabelFight = new javax.swing.JLabel();
        jLabelHumanScaleHealth = new javax.swing.JLabel();
        jLabelEnemyScaleHealth = new javax.swing.JLabel();
        jLabelExperience = new javax.swing.JLabel();
        jLabelPoints = new javax.swing.JLabel();
        jLabelExperienceScaleValue = new javax.swing.JLabel();
        jLabelPointsValue = new javax.swing.JLabel();
        jLabelLevelEnemy = new javax.swing.JLabel();
        jLabelTurn = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jLabelHumanName = new javax.swing.JLabel();
        jLabelStun = new javax.swing.JLabel();
        jButtonItems = new javax.swing.JButton();
        jDialogWin = new javax.swing.JDialog();
        jPanelWin = new javax.swing.JPanel();
        jLabelWinner = new javax.swing.JLabel();
        jButtonWinContinue = new javax.swing.JButton();
        jDialogFinishName = new javax.swing.JDialog();
        jPanelFinishName = new javax.swing.JPanel();
        jLabelYouWin = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelSetName = new javax.swing.JLabel();
        jLabelSetNameToTable = new javax.swing.JLabel();
        jButtonFinishGame = new javax.swing.JButton();
        jDialogTableRecords = new javax.swing.JDialog();
        jPanelTableRecords = new javax.swing.JPanel();
        jLabelTableRecords = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jButtonCloseTable = new javax.swing.JButton();
        jDialogWinTop = new javax.swing.JDialog();
        jPanelWinTop = new javax.swing.JPanel();
        jLabelWinYours = new javax.swing.JLabel();
        jLabelResultTop = new javax.swing.JLabel();
        jButtonCloseWinTop = new javax.swing.JButton();
        jDialogItems = new javax.swing.JDialog();
        jPanelItems = new javax.swing.JPanel();
        jLabelBagItems = new javax.swing.JLabel();
        jRadioButtonSmallItem = new javax.swing.JRadioButton();
        jRadioButtonBigItem = new javax.swing.JRadioButton();
        jRadioButtonCrossRelive = new javax.swing.JRadioButton();
        jButtonUseItem = new javax.swing.JButton();
        buttonGroupItems = new javax.swing.ButtonGroup();
        jDialogCantUseItem = new javax.swing.JDialog();
        jPanelCantUseItem = new javax.swing.JPanel();
        jLabelCantUseItem1 = new javax.swing.JLabel();
        jLabelCantUseItem2 = new javax.swing.JLabel();
        jButtonCantUseItemOK = new javax.swing.JButton();
        jPanelInitial = new javax.swing.JPanel();
        jLabelGameName = new javax.swing.JLabel();
        jButtonStartGame = new javax.swing.JButton();
        jButtonShowResult = new javax.swing.JButton();
        jLabelImageGame = new javax.swing.JLabel();
        jDialogChoseLocation = new javax.swing.JDialog();
        jPanelChoseLocation = new javax.swing.JPanel();
        jLabelCountLocation = new javax.swing.JLabel();
        jTextFieldCountLocation = new javax.swing.JTextField();
        jButtonChoseLocation = new javax.swing.JButton();
        jLabelLocation = new javax.swing.JLabel();
        jLabelLocationNumber = new javax.swing.JLabel();
        jLabelNextLocation = new javax.swing.JLabel();
        jDialogChosePlayer = new javax.swing.JDialog();
        jPanelChosePlayer = new javax.swing.JPanel();
        jLabelChooseFighter = new javax.swing.JLabel();
        jLabelImageFighter2 = new javax.swing.JLabel();
        jLabellImageFighter3 = new javax.swing.JLabel();
        jLabellImageFighter1 = new javax.swing.JLabel();
        jRadioButtonJhin = new javax.swing.JRadioButton();
        jRadioButtonKarina = new javax.swing.JRadioButton();
        jRadioButtonRammus = new javax.swing.JRadioButton();
        jButtonFighter = new javax.swing.JButton();
        buttonGroupFighter = new javax.swing.ButtonGroup();


        jPanelGameplay.setBackground(new java.awt.Color(255, 255, 255));

        this.jRadioButtonJhin.setActionCommand("Jhin");
        this.jRadioButtonKarina.setActionCommand("Karina");
        this.jRadioButtonRammus.setActionCommand("Rammus");

        jButtonAtack.setBackground(new java.awt.Color(255, 0, 0));
        jButtonAtack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonAtack.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAtack.setText("Атаковать");
        jButtonAtack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFight(evt);
            }
        });

        jButtonDefence.setBackground(new java.awt.Color(255, 204, 0));
        jButtonDefence.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonDefence.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDefence.setText("Защититься");
        jButtonDefence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefence(evt);
            }
        });

        jProgressBarHumanDamage.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBarHumanDamage.setForeground(new java.awt.Color(51, 255, 51));
        jProgressBarHumanDamage.setMaximum(80);
        jProgressBarHumanDamage.setMinimum(-1);

        jProgressBarEnemyDamage.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBarEnemyDamage.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBarEnemyDamage.setMinimum(-1);

        jLabelNameBoss.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNameBoss.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        jLabelEnemyDamage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnemyDamage.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelEnemyDamage.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEnemyDamage.setText("Damage");

        jLabelHumanDamage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumanDamage.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelHumanDamage.setForeground(new java.awt.Color(0, 0, 0));
        jLabelHumanDamage.setText("Damage");

        jLabelHumanDamageValue.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumanDamageValue.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelHumanDamageValue.setForeground(new java.awt.Color(255, 0, 0));
        jLabelHumanDamageValue.setText("16");

        jLabelEnemyDamageValue.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnemyDamageValue.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelEnemyDamageValue.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEnemyDamageValue.setText("16");

        jLabelLevel.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLevel.setText("0 уровень");

        jLabelFight.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFight.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        jLabelFight.setForeground(new java.awt.Color(0, 0, 153));
        jLabelFight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFight.setText("FIGHT");
        jLabelFight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHumanScaleHealth.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHumanScaleHealth.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelHumanScaleHealth.setForeground(new java.awt.Color(102, 102, 102));
        jLabelHumanScaleHealth.setText("80/80");

        jLabelEnemyScaleHealth.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEnemyScaleHealth.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelEnemyScaleHealth.setForeground(new java.awt.Color(102, 102, 102));
        jLabelEnemyScaleHealth.setText("80/80");

        jLabelExperience.setBackground(new java.awt.Color(255, 255, 255));
        jLabelExperience.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelExperience.setForeground(new java.awt.Color(128, 92, 31));
        jLabelExperience.setText("experience");

        jLabelPoints.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPoints.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelPoints.setForeground(new java.awt.Color(128, 92, 31));
        jLabelPoints.setText("points");

        jLabelExperienceScaleValue.setBackground(new java.awt.Color(255, 255, 255));
        jLabelExperienceScaleValue.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelExperienceScaleValue.setForeground(new java.awt.Color(113, 90, 16));
        jLabelExperienceScaleValue.setText("0/40");

        jLabelPointsValue.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPointsValue.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelPointsValue.setForeground(new java.awt.Color(113, 90, 16));
        jLabelPointsValue.setText("00");

        jLabelLevelEnemy.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLevelEnemy.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelLevelEnemy.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLevelEnemy.setText("1 уровень");

        jLabelTurn.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabelTurn.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelResult.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabelResult.setForeground(new java.awt.Color(204, 0, 0));
        jLabelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelHumanName.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        jLabelHumanName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHumanName.setText("");

        jLabelStun.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabelStun.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonItems.setBackground(new java.awt.Color(174, 183, 106));
        jButtonItems.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonItems.setForeground(new java.awt.Color(0, 0, 0));
        jButtonItems.setText("Предметы");
        jLabelLocation.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLocation.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelLocation.setForeground(new java.awt.Color(128, 92, 31));
        jLabelLocation.setText("location");

        jLabelLocationNumber.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLocationNumber.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelLocationNumber.setForeground(new java.awt.Color(113, 90, 16));
        jLabelLocationNumber.setText("1");
        jButtonItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGetItems(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanelGameplay);
        jPanelGameplay.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabelEnemyScaleHealth))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabelLocation)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFight, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelExperience))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jProgressBarEnemyDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(92, 92, 92)
                                                .addComponent(jLabelPoints))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addComponent(jLabelPointsValue)
                                                .addGap(108, 108, 108)
                                                .addComponent(jLabelExperienceScaleValue))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelEnemyDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelEnemyDamageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabelNameBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelImageEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabelTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelStun, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabelLocationNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonItems, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelLevel)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jProgressBarHumanDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelHumanScaleHealth))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelHumanDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelHumanDamageValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelImageHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelHumanName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonAtack, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButtonDefence, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabelLevelEnemy)
                    .addContainerGap(854, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelFight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBarHumanDamage, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jProgressBarEnemyDamage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabelHumanScaleHealth))
                            .addComponent(jLabelEnemyScaleHealth, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelExperience)
                            .addComponent(jLabelPoints))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelExperienceScaleValue)
                            .addComponent(jLabelPointsValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHumanDamage)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEnemyDamage)
                        .addComponent(jLabelEnemyDamageValue)
                        .addComponent(jLabelHumanDamageValue)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelImageEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNameBoss, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelLocationNumber)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabelLevel)
                                .addGap(7, 7, 7)
                                .addComponent(jLabelImageHuman, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStun, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHumanName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonItems, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonAtack, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(jButtonDefence, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                                .addComponent(jLabelLocation))
                        .addGap(14, 14, 14))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(229, 229, 229)
                    .addComponent(jLabelLevelEnemy)
                    .addContainerGap(380, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame.getContentPane());
        jFrame.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(jPanelGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGameplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelWin.setBackground(new java.awt.Color(179, 226, 217));

        jLabelWinner.setBackground(new java.awt.Color(204, 204, 204));
        jLabelWinner.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        jLabelWinner.setForeground(new java.awt.Color(204, 0, 0));
        jLabelWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinner.setText("jLabelWinner");
        jLabelWinner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNextLocation.setBackground(new java.awt.Color(204, 204, 204));
        jLabelNextLocation.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabelNextLocation.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNextLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNextLocation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNextLocation.setText("");

        jButtonWinContinue.setBackground(new java.awt.Color(114, 218, 142));
        jButtonWinContinue.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButtonWinContinue.setForeground(new java.awt.Color(0, 0, 0));
        jButtonWinContinue.setText("Дальше");
        jButtonWinContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWinContinue(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanelWin);
        jPanelWin.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButtonWinContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabelNextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(232, Short.MAX_VALUE)
                    .addComponent(jLabelNextLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)
                .addComponent(jLabelWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButtonWinContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialogWin.getContentPane());
        jDialogWin.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFinishName.setBackground(new java.awt.Color(255, 204, 255));

        jLabelYouWin.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelYouWin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelYouWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelYouWin.setText("Победа на вашей стороне");

        jTextFieldName.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelSetName.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelSetName.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSetName.setText("Введите имя своего персонажа для добавления");

        jLabelSetNameToTable.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelSetNameToTable.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSetNameToTable.setText("результата в таблицу рекордов");

        jButtonFinishGame.setBackground(new java.awt.Color(153, 153, 255));
        jButtonFinishGame.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonFinishGame.setForeground(new java.awt.Color(51, 51, 51));
        jButtonFinishGame.setText("Закончить игру");
        jButtonFinishGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinishGame(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanelFinishName);
        jPanelFinishName.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonFinishGame)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabelSetNameToTable))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelYouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSetName))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabelYouWin, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSetName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSetNameToTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFinishGame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialogFinishName.getContentPane());
        jDialogFinishName.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFinishName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFinishName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTableRecords.setBackground(new java.awt.Color(204, 204, 255));

        jLabelTableRecords.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabelTableRecords.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTableRecords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTableRecords.setText("Таблица рекордов");

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                String.class, Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableResult);

        jButtonCloseTable.setBackground(new java.awt.Color(255, 255, 153));
        jButtonCloseTable.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonCloseTable.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCloseTable.setText("Закрыть");
        jButtonCloseTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseTable(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanelTableRecords);
        jPanelTableRecords.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCloseTable, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabelTableRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelTableRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCloseTable, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialogTableRecords.getContentPane());
        jDialogTableRecords.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTableRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTableRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelWinTop.setBackground(new java.awt.Color(255, 204, 255));

        jLabelWinYours.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabelWinYours.setForeground(new java.awt.Color(255, 0, 0));
        jLabelWinYours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWinYours.setText("Победа на вашей стороне");

        jLabelResultTop.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelResultTop.setForeground(new java.awt.Color(102, 102, 102));
        jLabelResultTop.setText("К сожалению, Ваш результат не попал в топ 10");

        jButtonCloseWinTop.setBackground(new java.awt.Color(153, 153, 255));
        jButtonCloseWinTop.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonCloseWinTop.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCloseWinTop.setText("Закончить игру");
        jButtonCloseWinTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWinFinish(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanelWinTop);
        jPanelWinTop.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelWinYours, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabelResultTop, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButtonCloseWinTop, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelWinYours, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabelResultTop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButtonCloseWinTop, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialogWinTop.getContentPane());
        jDialogWinTop.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWinTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWinTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelItems.setBackground(new java.awt.Color(190, 182, 135));

        jLabelBagItems.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabelBagItems.setForeground(new java.awt.Color(51, 51, 51));
        jLabelBagItems.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBagItems.setText("Мешок предметов");

        jRadioButtonSmallItem.setBackground(new java.awt.Color(190, 182, 135));
        jRadioButtonSmallItem.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonSmallItem.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonSmallItem.setText("Малое зелье лечение, 0 шт");

        jRadioButtonBigItem.setBackground(new java.awt.Color(190, 182, 135));
        jRadioButtonBigItem.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonBigItem.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonBigItem.setText("Большое зелье лечение, 0 шт");
        jRadioButtonCrossRelive.setBackground(new java.awt.Color(190, 182, 135));
        jRadioButtonCrossRelive.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jRadioButtonCrossRelive.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonCrossRelive.setText("Крест возрождения, 0 шт");

        jButtonUseItem.setBackground(new java.awt.Color(239, 237, 14));
        jButtonUseItem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButtonUseItem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUseItem.setText("Использовать");
        jButtonUseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUseItem(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanelItems);
        jPanelItems.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonBigItem)
                            .addComponent(jRadioButtonCrossRelive, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSmallItem, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBagItems, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButtonUseItem)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelBagItems, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jRadioButtonSmallItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonBigItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCrossRelive)
                .addGap(50, 50, 50)
                .addComponent(jButtonUseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialogItems.getContentPane());
        jDialogItems.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCantUseItem.setBackground(new java.awt.Color(243, 120, 120));

        jLabelCantUseItem1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelCantUseItem1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCantUseItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantUseItem1.setText("Вы не можете использовать ");

        jLabelCantUseItem2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabelCantUseItem2.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCantUseItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantUseItem2.setText("этот предмет");

        jButtonCantUseItemOK.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCantUseItemOK.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonCantUseItemOK.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCantUseItemOK.setText("ОК");
        jButtonCantUseItemOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCantUseItemOK(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanelCantUseItem);
        jPanelCantUseItem.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelCantUseItem1)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelCantUseItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButtonCantUseItemOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelCantUseItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCantUseItem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jButtonCantUseItemOK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialogCantUseItem.getContentPane());
        jDialogCantUseItem.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCantUseItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCantUseItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLabelCountLocation.setText("Выберите количество локаций");

        jButtonChoseLocation.setText("Начать");
        jButtonChoseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoseLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChoseLocationLayout = new javax.swing.GroupLayout(jPanelChoseLocation);
        jPanelChoseLocation.setLayout(jPanelChoseLocationLayout);
        jPanelChoseLocationLayout.setHorizontalGroup(
                jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                .addGroup(jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addGroup(jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldCountLocation)
                                                        .addComponent(jLabelCountLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(jButtonChoseLocation)))
                                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanelChoseLocationLayout.setVerticalGroup(
                jPanelChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChoseLocationLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelCountLocation)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldCountLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonChoseLocation)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogChoseLocationLayout = new javax.swing.GroupLayout(jDialogChoseLocation.getContentPane());
        jDialogChoseLocation.getContentPane().setLayout(jDialogChoseLocationLayout);
        jDialogChoseLocationLayout.setHorizontalGroup(
                jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChoseLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogChoseLocationLayout.setVerticalGroup(
                jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 206, Short.MAX_VALUE)
                        .addGroup(jDialogChoseLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChoseLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );


        jLabelChooseFighter.setBackground(new java.awt.Color(204, 204, 204));
        jLabelChooseFighter.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        jLabelChooseFighter.setForeground(new java.awt.Color(204, 0, 0));
        jLabelChooseFighter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChooseFighter.setText("Choose your fighter");
        jLabelChooseFighter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRadioButtonJhin.setText("Jhin");

        jRadioButtonKarina.setText("Karina");

        jRadioButtonRammus.setText("Rammus");

        jButtonFighter.setText("Выбрать");
        jButtonFighter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFighterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelChosePlayerLayout = new javax.swing.GroupLayout(jPanelChosePlayer);
        jPanelChosePlayer.setLayout(jPanelChosePlayerLayout);
        jPanelChosePlayerLayout.setHorizontalGroup(
                jPanelChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChosePlayerLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabellImageFighter1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelImageFighter2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabellImageFighter3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
                        .addGroup(jPanelChosePlayerLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelChooseFighter, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChosePlayerLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jRadioButtonJhin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonFighter)
                                        .addComponent(jRadioButtonKarina))
                                .addGap(205, 205, 205)
                                .addComponent(jRadioButtonRammus)
                                .addGap(119, 119, 119))
        );
        jPanelChosePlayerLayout.setVerticalGroup(
                jPanelChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelChosePlayerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelChooseFighter, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addGroup(jPanelChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelImageFighter2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabellImageFighter3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabellImageFighter1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButtonJhin)
                                        .addComponent(jRadioButtonRammus)
                                        .addComponent(jRadioButtonKarina))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jButtonFighter)
                                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jDialogChosePlayerLayout = new javax.swing.GroupLayout(jDialogChosePlayer.getContentPane());
        jDialogChosePlayer.getContentPane().setLayout(jDialogChosePlayerLayout);
        jDialogChosePlayerLayout.setHorizontalGroup(
                jDialogChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 936, Short.MAX_VALUE)
                        .addGroup(jDialogChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChosePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogChosePlayerLayout.setVerticalGroup(
                jDialogChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 574, Short.MAX_VALUE)
                        .addGroup(jDialogChosePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelChosePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInitial.setBackground(new java.awt.Color(255, 255, 255));
        jLabellImageFighter1.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/Jhin.png")));
        jLabelImageFighter2.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/Karina.png")));
        jLabellImageFighter3.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/Rammus.png")));

        jLabelGameName.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        jLabelGameName.setForeground(new java.awt.Color(204, 204, 0));
        jLabelGameName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGameName.setText("Mortal Kombat");

        jButtonStartGame.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonStartGame.setText("Начать новую игру");
        jButtonStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartGame(evt);
            }
        });

        jButtonShowResult.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonShowResult.setText("Посмотреть таблицу \nрезультатов");
        jButtonShowResult.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButtonShowResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetResults(evt);
            }
        });

        jLabelImageGame.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/logo.png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanelInitial);
        jPanelInitial.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonShowResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabelGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabelImageGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelImageGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShowResult, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInitial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInitial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Кнопка запуска игры
     */
    private void jButtonStartGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialogChoseLocation.setVisible(true);
        jDialogChoseLocation.setBounds(100, 100, 400, 250);
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Кнопка атаки противника
     */
    private void jButtonFight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        game.fight.Hit( human, enemy, 1, jLabelEnemyScaleHealth, jLabelHumanScaleHealth, jDialogWin,
                jLabelWinner, game.action, jProgressBarHumanDamage, jProgressBarEnemyDamage, jDialogFinishName,
                jDialogWinTop, jFrame, game.xlsxManipulation.getResults(), jLabelYouWin, jLabelWinYours,
                jLabelTurn, jLabelStun, jLabelResult, items, jRadioButtonCrossRelive,jLabelNextLocation);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Кнопка защиты противника
     */
    private void jButtonDefence(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        game.fight.Hit( human, enemy, 0, jLabelEnemyScaleHealth, jLabelHumanScaleHealth, jDialogWin,
                jLabelWinner, game.action, jProgressBarHumanDamage, jProgressBarEnemyDamage, jDialogFinishName,
                jDialogWinTop, jFrame, game.xlsxManipulation.getResults(), jLabelYouWin, jLabelWinYours,
                jLabelTurn, jLabelStun, jLabelResult, items, jRadioButtonCrossRelive, jLabelNextLocation);
    }//GEN-LAST:event_jButton4ActionPerformed
    /**
     * Кнопка продолжения игры после завершения раунда
     */
    private void jButtonWinContinue(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        enemy=game.fight.NewRound(human, jLabelImageEnemy, jProgressBarHumanDamage, jProgressBarEnemyDamage,
                jLabelNameBoss, jLabelEnemyDamageValue, jLabelEnemyScaleHealth, game.action);

        
        game.change.NewRoundTexts(human, enemy, jProgressBarHumanDamage, jProgressBarEnemyDamage,
                jLabelPointsValue, jLabelExperienceScaleValue, jLabelLevel, jLabelLevelEnemy, jLabelHumanScaleHealth, jLabelEnemyScaleHealth, jLabelHumanDamageValue,
                jLabelTurn, jLabelResult, game.fight.i, items, jRadioButtonSmallItem, jRadioButtonBigItem, jRadioButtonCrossRelive,jLabelLocationNumber, game.fight.location,
                jLabelHumanName, jLabelImageHuman, human.getName());

        jDialogWin.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    /**
     * Кнопка завершения игры
     */
    private void jButtonFinishGame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            game.xlsxManipulation.EndGameTop(human, jTextFieldName, jTableResult);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogFinishName.dispose();
        jTextFieldName.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed
    /**
     * Кнопка закрытия таблицы рейтинга
     */
    private void jButtonCloseTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialogTableRecords.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed
    /**
     * Кнопка открытия таблицы с рейтингом
     */
    private void jButtonSetResults(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialogTableRecords.setVisible(true);
        jDialogTableRecords.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Кнопка завершения игры при попадании в топ 10 игроков
     */
    private void jButtonWinFinish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jDialogWinTop.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
    /**
     * Кнопка использования предметов
     */
    private void jButtonUseItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(jRadioButtonSmallItem.isSelected()){
            nameButton="jRadioButtonSmallItem";
        }
        if(jRadioButtonBigItem.isSelected()){
            nameButton="jRadioButtonBigItem";
        }
        if(jRadioButtonCrossRelive.isSelected()){
            nameButton="jRadioButtonCrossRelive";
        }
        game.action.UseItem(human, items, nameButton, jDialogCantUseItem, jDialogItems);
        game.action.HP(human, jProgressBarHumanDamage);
        jLabelHumanScaleHealth.setText(human.getHealth() + "/" + human.getMaxHealth());
        game.change.BagText(items, jRadioButtonSmallItem, jRadioButtonBigItem, jRadioButtonCrossRelive);
    }//GEN-LAST:event_jButton9ActionPerformed
    /**
     * Кнопка получения списка доступных предметов
     */
    private void jButtonGetItems(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jDialogItems.setVisible(true);
        jDialogItems.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_jButton10ActionPerformed
    /**
     * Кнопка невозможности использования предмета
     */
    private void jButtonCantUseItemOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jDialogCantUseItem.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed
    /**
     * Кнопка выбора количества локаций в игре
     */
    private void jButtonChoseLocationActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            game.location = Integer.parseInt(jTextFieldCountLocation.getText());
            if(game.location<=0)throw new Exception();

            jDialogChoseLocation.dispose();

            jDialogChosePlayer.setVisible(true);
            jDialogChosePlayer.setBounds(0, 0, 940, 588);

        }catch (Exception e){
            JOptionPane.showMessageDialog (null, "Ошибка ввода локаций", "Oшибка", JOptionPane.ERROR_MESSAGE);
            jTextFieldCountLocation.setText("");
        }

    }

    /**
     * Кнопка выбора бойца
     * @param evt
     */
    private void jButtonFighterActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String name = buttonGroupFighter.getSelection().getActionCommand();
            if(name==null)throw new Exception("Боец не выбран");

            jDialogChosePlayer.dispose();

            jFrame.setVisible(rootPaneCheckingEnabled);
            jFrame.setSize(1000,700);

            human = game.NewHuman(jProgressBarHumanDamage, game.location, name);

            enemy = game.NewEnemy(jLabelImageEnemy, jLabelNameBoss, jLabelEnemyDamageValue, jLabelEnemyScaleHealth, jProgressBarEnemyDamage);

            game.change.NewRoundTexts(human, enemy, jProgressBarHumanDamage, jProgressBarEnemyDamage,
                    jLabelPointsValue, jLabelExperienceScaleValue, jLabelLevel, jLabelLevelEnemy, jLabelHumanScaleHealth, jLabelEnemyScaleHealth, jLabelHumanDamageValue,
                    jLabelTurn, jLabelResult, game.fight.i, items, jRadioButtonSmallItem, jRadioButtonBigItem, jRadioButtonCrossRelive, jLabelLocationNumber, game.fight.location,
                    jLabelHumanName, jLabelImageHuman, name);

            jTextFieldCountLocation.setText("");

        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e.getMessage(), "Oшибка", JOptionPane.ERROR_MESSAGE);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupItems;
    private javax.swing.JButton jButtonStartGame;
    private javax.swing.JButton jButtonItems;
    private javax.swing.JButton jButtonCantUseItemOK;
    private javax.swing.JButton jButtonShowResult;
    private javax.swing.JButton jButtonAtack;
    private javax.swing.JButton jButtonDefence;
    private javax.swing.JButton jButtonWinContinue;
    private javax.swing.JButton jButtonFinishGame;
    private javax.swing.JButton jButtonCloseTable;
    private javax.swing.JButton jButtonCloseWinTop;
    private javax.swing.JButton jButtonUseItem;
    private javax.swing.JDialog jDialogWin;
    private javax.swing.JDialog jDialogFinishName;
    private javax.swing.JDialog jDialogTableRecords;
    private javax.swing.JDialog jDialogWinTop;
    private javax.swing.JDialog jDialogItems;
    private javax.swing.JDialog jDialogCantUseItem;
    private javax.swing.JFrame jFrame;
    private javax.swing.JLabel jLabelGameName;
    private javax.swing.JLabel jLabelEnemyDamageValue;
    private javax.swing.JLabel jLabelFight;
    private javax.swing.JLabel jLabelHumanScaleHealth;
    private javax.swing.JLabel jLabelEnemyScaleHealth;
    private javax.swing.JLabel jLabelExperience;
    private javax.swing.JLabel jLabelPoints;
    private javax.swing.JLabel jLabelExperienceScaleValue;
    private javax.swing.JLabel jLabelPointsValue;
    private javax.swing.JLabel jLabelWinner;
    private javax.swing.JLabel jLabelLevelEnemy;
    private javax.swing.JLabel jLabelImageHuman;
    private javax.swing.JLabel jLabelYouWin;
    private javax.swing.JLabel jLabelSetName;
    private javax.swing.JLabel jLabelSetNameToTable;
    private javax.swing.JLabel jLabelTableRecords;
    private javax.swing.JLabel jLabelWinYours;
    private javax.swing.JLabel jLabelResultTop;
    private javax.swing.JLabel jLabelTurn;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelHumanName;
    private javax.swing.JLabel jLabelStun;
    private javax.swing.JLabel jLabelImageGame;
    private javax.swing.JLabel jLabelBagItems;
    private javax.swing.JLabel jLabelCantUseItem1;
    private javax.swing.JLabel jLabelCantUseItem2;
    private javax.swing.JLabel jLabelImageEnemy;
    private javax.swing.JLabel jLabelNameBoss;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelEnemyDamage;
    private javax.swing.JLabel jLabelHumanDamage;
    private javax.swing.JLabel jLabelHumanDamageValue;
    private javax.swing.JPanel jPanelInitial;
    private javax.swing.JPanel jPanelGameplay;
    private javax.swing.JPanel jPanelWin;
    private javax.swing.JPanel jPanelFinishName;
    private javax.swing.JPanel jPanelTableRecords;
    private javax.swing.JPanel jPanelWinTop;
    private javax.swing.JPanel jPanelItems;
    private javax.swing.JPanel jPanelCantUseItem;
    private javax.swing.JProgressBar jProgressBarHumanDamage;
    private javax.swing.JProgressBar jProgressBarEnemyDamage;
    private javax.swing.JRadioButton jRadioButtonSmallItem;
    private javax.swing.JRadioButton jRadioButtonBigItem;
    private javax.swing.JRadioButton jRadioButtonCrossRelive;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldCountLocation;
    private javax.swing.JPanel jPanelChoseLocation;
    private javax.swing.JLabel jLabelCountLocation;
    private javax.swing.JDialog jDialogChoseLocation;
    private javax.swing.JButton jButtonChoseLocation;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelLocationNumber;
    private javax.swing.JLabel jLabelNextLocation;
    private javax.swing.ButtonGroup buttonGroupFighter;
    private javax.swing.JButton jButtonFighter;
    private javax.swing.JDialog jDialogChosePlayer;
    private javax.swing.JPanel jPanelChosePlayer;
    private javax.swing.JRadioButton jRadioButtonJhin;
    private javax.swing.JRadioButton jRadioButtonKarina;
    private javax.swing.JRadioButton jRadioButtonRammus;
    private javax.swing.JLabel jLabellImageFighter1;
    private javax.swing.JLabel jLabellImageFighter3;
    private javax.swing.JLabel jLabelChooseFighter;
    private javax.swing.JLabel jLabelImageFighter2;


    // End of variables declaration//GEN-END:variables
}
